Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'payload.session.keepalive_timeout_seconds', line 1, position 314. ---> System.InvalidCastException: Null object cannot be converted to a value type.    at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)    at Twitch.Base.Clients.EventSubClient.ProcessReceivedPacket(String packet)